<?php
/**
 * @copyright Copyright (c) 2017 a4logic Colombia (https://www.a4logic.com)
 */
?>
<form action="<?php echo $this->getGatewayUrl() ?>" method="POST" name="payform">
    <?php foreach ($this->getOrderCreateData() as $name => $value): ?>
    <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>" />
    <?php endforeach; ?>
</form>
<script language="JavaScript" type="text/javascript">
    <!--
    document.forms['payform'].submit();
    -->
</script>