<div class="container">
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl();
$urls = $block->getUrl('customform/index');
?>
    <form class="form-horizontal" id="form_height" method="post" enctype="multipart/form-data" action="<?php echo $urls; ?>">
<div class="form-group"><label for="nombre">Nombre*:</label><input id="nombre" class="form-control" maxlength="256" name="Nombre" type="text" placeholder="Ingresa tu nombre" /></div>
<div class="form-group"><label for="email">E-mail*:</label> <input id="email" class="form-control" maxlength="256" name="Email" type="email" placeholder="Ingresa tu correo" /></div>
<div class="form-group"><label for="telefono">Telefono*:</label><input id="telefono" class="form-control" maxlength="256" name="Telefono" type="text" placeholder="Ingresa tu telefono" /></div>
<input class="btn-contacto round-btn w-button" type="submit" value="ENVIAR" />

       

    </form>
</div>

