<?php

/**
 * @var Cleavercoder\Advanceshiping\Block\Shipingform $block
 */

$data =  $block->sayHello();
 //$xml = simplexml_load_string($data);

print_r(  [
            [    'value' => '05002000',
                'label' => 'ABEJORRAL' 
            ],

            [
               'value' => '54003000',
               'label' => 'ABREGO'    
             ],

             [  'value' => '05004000',
                 'label' => 'ABRIAQUI'  
            ]
         ]);
// echo "<pre>";
//             print_r( $_SESSION['arry']);
//             echo "</pre>";
echo "this  is workkingg";

?>

